name: 游 Feature Request
description: Foresl친 en ny funksjon eller forbedring
title: "[FEAT]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Er problemet relatert til et problem?
      description: Beskriv problemet du pr칮ver 친 l칮se.
      placeholder: Jeg blir frustrert n친r jeg m친...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Foresl친tt l칮sning
      description: Hvordan ser du for deg at det skal fungere?
    validations:
      required: true